# Generated by Django 4.2.3 on 2024-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_keys_madin_alter_keys_minda_alter_keys_saran"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keys",
            name="madin",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="keys",
            name="minda",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="keys",
            name="saran",
            field=models.IntegerField(default=0),
        ),
    ]
